name: Oppija-raamit

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'

      - uses: actions/setup-node@v3
        with:
          node-version: '9.11.1'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Build with Maven
        env:
          CI: false
        run: mvn clean install -B -Dbranch=${GITHUB_REF_NAME} -Drevision=${GITHUB_SHA} -DbuildNumber=${GITHUB_RUN_NUMBER}

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            target
          key: ${{ github.sha }}

  deploy-container:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            target
          key: ${{ github.sha }}

      - name: Build and deploy Docker container
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          export ARTIFACT_NAME="oppija-raamit"
          mv -v target/oppija-raamit-*.jar $DOCKER_BUILD_DIR/artifact/oppija-raamit.jar
          export BASE_IMAGE="baseimage-fatjar-openjdk8:master"
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-fatjar.sh $ARTIFACT_NAME
          ./ci-tools/github-build/upload-image.sh $ARTIFACT_NAME
