name: Oppija-raamit

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

permissions:
  id-token: write
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - uses: actions/setup-node@v4
        with:
          node-version: '9.11.1'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Build with Maven
        env:
          CI: false
        run: mvn clean install -B -Dbranch=${GITHUB_REF_NAME} -Drevision=${GITHUB_SHA} -DbuildNumber=${GITHUB_RUN_NUMBER}

      - uses: actions/cache@v4
        id: restore-build
        with:
          path: |
            target
          key: ${{ github.sha }}

  deploy-container:
    needs: test-and-build
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: oppija-raamit
      base-image: baseimage-fatjar-openjdk17:master
      configfolder: config
      jarfile: oppija-raamit-*.jar
      jarfolder: target
    secrets:
        AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
